// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutocompleteController from "./autocomplete_controller"
application.register("autocomplete", AutocompleteController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)

import IngredientSearchController from "./ingredient_search_controller"
application.register("ingredient-search", IngredientSearchController)

import LoadingController from "./loading_controller"
application.register("loading", LoadingController)

import LikeController from "./like_controller"
application.register("like", LikeController)
